#!/usr/bin/env python3
"""Comprehensive fix for sportpredict/index.html encoding corruption."""
import sys
sys.stdout.reconfigure(encoding='utf-8')

filepath = r'C:\Users\wzgui\.openclaw-autoclaw\workspace\sportpredict\index.html'

with open(filepath, 'rb') as f:
    raw = f.read()
content = raw.decode('utf-8', errors='replace')

# ============================================================
# STEP 1: Add missing hero keys after heroTitle in existing I18N blocks
# ============================================================

hero_keys_to_add = {
    'zh': """\
    heroSubtitle: '全球体育赔率数据分析平台',
    heroTag1: '📊 实时赔率',
    heroTag2: '🎯 市场概率',
    heroTag3: '🔮 差异分析',
    heroBtnAnalyze: '📊 开始分析',
    heroBtnFavorites: '⭐ 收藏赛事',""",
    'en': """\
    heroSubtitle: 'Global Sports Odds Data Analysis Platform',
    heroTag1: '📊 Live Odds',
    heroTag2: '🎯 Market Probability',
    heroTag3: '🔮 Discrepancy Analysis',
    heroBtnAnalyze: '📊 Start Analysis',
    heroBtnFavorites: '⭐ Favorites',""",
    'es': """\
    heroSubtitle: 'Plataforma global de análisis de datos de cuotas deportivas',
    heroTag1: '📊 Cuotas en vivo',
    heroTag2: '🎯 Probabilidad de mercado',
    heroTag3: '🔮 Análisis de discrepancia',
    heroBtnAnalyze: '📊 Iniciar análisis',
    heroBtnFavorites: '⭐ Favoritos',""",
    'pt': """\
    heroSubtitle: 'Plataforma global de análise de dados de odds esportivas',
    heroTag1: '📊 Odds ao vivo',
    heroTag2: '🎯 Probabilidade de mercado',
    heroTag3: '🔮 Análise de discrepância',
    heroBtnAnalyze: '📊 Iniciar análise',
    heroBtnFavorites: '⭐ Favoritos',""",
    'ar': """\
    heroSubtitle: 'منصة عالمية لتحليل بيانات احتمالات الرياضة',
    heroTag1: '📊 احتمالات مباشرة',
    heroTag2: '🎯 احتمال السوق',
    heroTag3: '🔮 تحليل التباين',
    heroBtnAnalyze: '📊 بدء التحليل',
    heroBtnFavorites: '⭐ المفضلة',""",
}

# For each language, find "heroTitle: '🏆 SportPredict'," in I18N block
# and add hero keys after it
i18n_start = content.find('const I18N = {')
new_i18n_start = content.find('const NEW_I18N = {')

import re

for lang, hero_text in hero_keys_to_add.items():
    # Find heroTitle line within I18N block
    # Pattern: look for the heroTitle line in the context of the specific language
    # We need to find it within the I18N block only
    
    # Search for the pattern in the I18N portion
    i18n_portion = content[i18n_start:new_i18n_start]
    
    # Find "    heroTitle: '🏆 SportPredict'," 
    pattern = r"(    heroTitle: '🏆 SportPredict',)"
    matches = list(re.finditer(pattern, i18n_portion))
    
    for m in reversed(matches):  # Reverse to preserve positions
        pos = i18n_start + m.end()
        # Insert hero keys after heroTitle line
        content = content[:pos] + '\n' + hero_text + content[pos:]
        print(f"  Added hero keys after heroTitle at char {pos}")

print("Step 1 done: Added hero keys to existing I18N blocks\n")

# ============================================================
# STEP 2: Insert missing ja, ko, ru, fr, de blocks in I18N
# ============================================================

# We need to insert after the ar block's closing "  },"
# The ar block ends with "  }," before "};"

# Find the ar block end (right before "};\nconst NEW_I18N")
ar_block_end_pattern = r"(    heroBtnFavorites: '⭐ المفضلة',\n  },\n)(\};)"
ar_match = re.search(ar_block_end_pattern, content)

if not ar_match:
    # Try alternate: find the }, right before }; at end of I18N
    i18n_end = content.find('};', content.find('const I18N = {'))
    # Find the last "  }," before the "};"
    last_block_end = content.rfind('  },', i18n_start, i18n_end)
    insert_pos = last_block_end + len('  },')
    print(f"  Inserting after ar block at char {insert_pos}")
else:
    insert_pos = ar_match.start(2)
    print(f"  Found ar block end at char {insert_pos}")

# Complete I18N blocks for ja, ko, ru, fr, de
# Based on the structure from earlier reads, with correct translations

ja_block = """  ja: {
    sidebarLogo: '全スポーツ分析',
    sidebarFooter: 'データは参考用 · 投資アドバイスではありません',
    tabMatches: '試合一覧',
    tabCombos: 'データインサイト',
    tabDashboard: 'ダッシュボード',
    pageTitle: '{emoji} {sport}分析',
    homeTeam: 'ホーム',
    awayTeam: 'アウェイ',
    draw: '引き分け',
    confidence: 'データ整合性',
    noMatches: '{sport}の試合データがありません',
    all: 'すべて',
    combo2: '{sport} ダブルコンボ',
    combo3: '{sport} トリプルコンボ',
    combo2Label: 'ダブル',
    combo3Label: 'トリプル',
    crossCombo: '🌍 競技横断インサイト',
    crossCombo3: '競技横断トリプル',
    comboWinRate: '総合勝率',
    lowRisk: '低リスク',
    mediumRisk: '中リスク',
    highRisk: '高リスク',
    dashHitRate: '📊 インプライド勝率分布',
    dashHot: '🔥 トレンド試合',
    dashArb: '🌟 オッズ差異の機会',
    dashArbNone: 'オッズ差異の機会なし',
    dashArbDesc: '差異率',
    watchLive: '📺 観戦する',
    modalTitle: '📺 公式生放送チャンネル',
    modalDisclaimer: '⚖️ 公式の合法チャンネルで視聴してください',
    vs: 'vs',
    refreshOdds: 'オッズ更新',
    loading: '読み込み中...',
    loadError: '読み込み失敗',
    retry: '再試行',
    noData: 'データなし',
    oddsCompare: 'オッズ比較',
    showOdds: 'オッズ表示',
    hideOdds: 'オッズ非表示',
    impliedProb: 'インプライド勝率',
    arbOpportunity: 'オッズ差異',
    arbProfit: '差異率',
    apiRemaining: 'API残り',
    bookmaker: 'ブックメーカー',
    bestOdds: '最高オッズ',
    sportSoccer: 'サッカー',
    sportBasketball: 'バスケットボール',
    sportBaseball: '野球',
    sportIceHockey: 'アイスホッケー',
    sportTennis: 'テニス',
    sportAmericanFootball: 'アメフト',
    sportBoxing: 'ボクシング',
    sportMma: 'MMA',
    sportCricket: 'クリケット',
    sportRugby: 'ラグビー',
    sportEsports: 'eスポーツ',
    sportAussieRules: 'オージールール',
    sportGolf: 'ゴルフ',
    sportDarts: 'ダーツ',
    sportCycling: 'サイクリング',
    sportSnooker: 'スヌーカー',
    sportVolleyball: 'バレーボール',
    sportHandball: 'ハンドボール',
    sportFutsal: 'フットサル',
    sportTableTennis: '卓球',
    sportBadminton: 'バドミントン',
    chFIFA: 'FIFA+',
    chFIFADesc: 'FIFA公式ストリーミング',
    chLeagueOfficial: 'リーグ公式放送',
    chLeagueOfficialDesc: '各リーグ公式デジタル放送',
    chNBALeaguePass: 'NBA League Pass',
    chNBALeaguePassDesc: 'NBA公式ストリーミングサブスク',
    chESPNPlus: 'ESPN+',
    chESPNPlusDesc: 'ESPNストリーミングサブスク',
    chEurosport: 'Eurosport',
    chEurosportDesc: 'ヨーロッパスポーツストリーミング',
    chMLBtv: 'MLB.tv',
    chMLBtvDesc: 'MLB公式ストリーミングサブスク',
    chNFLGamePass: 'NFL Game Pass',
    chNFLGamePassDesc: 'NFL公式ストリーミングサブスク',
    chNHLtv: 'NHL.tv',
    chNHLtvDesc: 'NHL公式ストリーミングサブスク',
    chYoutubeSports: 'YouTube Sports',
    chYoutubeSportsDesc: 'YouTube Sportsチャンネル',
    chDAZN: 'DAZN',
    chDAZNDesc: 'グローバルスポーツストリーミングプラットフォーム',
    disclaimer: '⚠️ 免責事項：すべての分析データは市場オッズに基づき、参考用であり、投資アドバイスではありません。',
    disclaimer2: '試合結果は多くの要因に影響されます。過去のデータは将来の成果を保証しません。',
    heatUnit: '試合',
    // Legal pages
    privacyTitle: 'プライバシーポリシー',
    privacyP1: '最終更新：2026年6月3日',
    privacyH1: 'データ収集',
    privacyP2: 'SportPredictが収集するデータは以下のみです：言語設定（ブラウザにローカル保存）、APIキャッシュデータ（オッズ情報、5分後に期限切れ）。個人識別情報は収集しません。',
    privacyH2: 'Cookieの使用',
    privacyP3: '本サイトはlocalStorageを使用して言語設定とCookie同意状態を保存します。Google AdSenseを通じてCookieを使用し、パーソナライズされた広告を表示する場合があります。ブラウザ設定からCookieを管理できます。',
    privacyH3: 'サードパーティサービス',
    privacyP4: 'The Odds APIを使用してスポーツオッズデータを取得し、Google AdSenseを使用して広告を表示する場合があります。これらのサービスにはそれぞれのプライバシーポリシーがあります。',
    privacyH4: 'GDPRの権利',
    privacyP5: 'GDPRに基づき、個人データへのアクセス、訂正、削除の権利があります。権利を行使するには、下記の連絡先までご連絡ください。',
    privacyH5: 'お問い合わせ',
    aboutTitle: 'SportPredictについて',
    aboutP1: 'SportPredictは、世界中のスポーツ愛好者に市場データに基づく試合統計と確率分析を提供する専門的なスポーツデータ分析プラットフォームです。',
    aboutP2: '私たちの使命は、透明なデータ可視化を通じて、スポーツイベントにおける市場確率と統計トレンドの理解を支援することです。すべての分析は公開市場データに基づき、数学的モデルを使用して計算されています。',
    aboutP3: '⚠️ 重要：SportPredictは賭博サービスを提供せず、料金も徴収せず、いかなる形態のギャンブルも奨励または促進しません。本サイトの全コンテンツは情報参考および学術研究のみを目的としています。',
    termsTitle: '利用規約',
    termsP1: '本ウェブサイトを使用することにより、以下の規約に同意したものとみなされます：',
    termsP2: '1. 本サイトで提供されるすべてのデータと分析は参考用であり、賭博アドバイスを構成しません。',
    termsP3: '2. ユーザーはデータの正確性と適用性を独自に判断し、使用のリスクを負担してください。',
    termsP4: '3. 本サイトのコンテンツは知的財産権により保護されており、許可なく複製または再配布することはできません。',
    termsP5: '4. 本サイトはデータのリアルタイム性と正確性を保証せず、市場データに遅延が生じる場合があります。',
    cookieText: '本ウェブサイトはCookieを使用してエクスペリエンスを向上させ、Google AdSenseを通じて広告を表示する場合があります。継続して使用することにより、',
    cookieLink: 'プライバシーポリシー',
    cookieAccept: '同意する',
    footerDisclaimer: '⚠️ SportPredictはスポーツデータ分析プラットフォームであり、賭博サービスを提供せず、料金も徴収しません。すべてのデータは分析参考用です。',
    footerAbout: '私たちについて',
    footerPrivacy: 'プライバシーポリシー',
    footerTerms: '利用規約',
    footerContact: 'お問い合わせ',
    allEventsGuide: 'サイドバーのリーグをクリックしてデータをロード。オッズは5分間キャッシュされます。',
    clickToLoadOdds: '上のリーグ名をクリックしてオッズデータをロード',
    apiQuotaExceeded: 'APIクォータを超えました。来月のリセットをお待ちください。',
    apiQuotaHint: '無料プラン：月500リクエスト',
    heroTitle: '🏆 SportPredict',
    heroSubtitle: 'グローバルスポーツオッズデータ分析プラットフォーム',
    heroTag1: '📊 リアルタイムオッズ',
    heroTag2: '🎯 市場確率',
    heroTag3: '🔮 差異分析',
    heroBtnAnalyze: '📊 分析開始',
    heroBtnFavorites: '⭐ お気に入り',
  },"""

ko_block = """  ko: {
    sidebarLogo: '전체 스포츠 분석',
    sidebarFooter: '데이터는 참고용 · 금융 조언이 아닙니다',
    tabMatches: '경기 목록',
    tabCombos: '데이터 인사이트',
    tabDashboard: '대시보드',
    pageTitle: '{emoji} {sport} 분석',
    homeTeam: '홈',
    awayTeam: '원정',
    draw: '무승부',
    confidence: '데이터 일관성',
    noMatches: '{sport} 경기 데이터 없음',
    all: '전체',
    combo2: '{sport} 더블 콤보',
    combo3: '{sport} 트리플 콤보',
    combo2Label: '더블',
    combo3Label: '트리플',
    crossCombo: '🌍 종목 교차 인사이트',
    crossCombo3: '교차 트리플',
    comboWinRate: '종합 승률',
    lowRisk: '저위험',
    mediumRisk: '중위험',
    highRisk: '고위험',
    dashHitRate: '📊 내재 승률 분포',
    dashHot: '🔥 인기 경기',
    dashArb: '🌟 배당률 차이 기회',
    dashArbNone: '배당률 차이 기회 없음',
    dashArbDesc: '차이율',
    watchLive: '📺 시청하기',
    modalTitle: '📺 공식 생중계 채널',
    modalDisclaimer: '⚖️ 공식 합법 채널을 통해 시청하세요',
    vs: 'vs',
    refreshOdds: '배당률 새로고침',
    loading: '로딩 중...',
    loadError: '로딩 실패',
    retry: '재시도',
    noData: '데이터 없음',
    oddsCompare: '배당률 비교',
    showOdds: '배당률 보기',
    hideOdds: '배당률 숨기기',
    impliedProb: '내재 확률',
    arbOpportunity: '배당률 차이',
    arbProfit: '차이율',
    apiRemaining: 'API 남은',
    bookmaker: '북메이커',
    bestOdds: '최고 배당률',
    sportSoccer: '축구',
    sportBasketball: '농구',
    sportBaseball: '야구',
    sportIceHockey: '아이스하키',
    sportTennis: '테니스',
    sportAmericanFootball: '미식축구',
    sportBoxing: '복싱',
    sportMma: 'MMA',
    sportCricket: '크리켓',
    sportRugby: '럭비',
    sportEsports: 'e스포츠',
    sportAussieRules: '호주식 축구',
    sportGolf: '골프',
    sportDarts: '다트',
    sportCycling: '사이클링',
    sportSnooker: '스누커',
    sportVolleyball: '배구',
    sportHandball: '핸드볼',
    sportFutsal: '풋살',
    sportTableTennis: '탁구',
    sportBadminton: '배드민턴',
    chFIFA: 'FIFA+',
    chFIFADesc: 'FIFA 공식 스트리밍 플랫폼',
    chLeagueOfficial: '리그 공식 방송',
    chLeagueOfficialDesc: '공식 디지털 방송 플랫폼',
    chNBALeaguePass: 'NBA League Pass',
    chNBALeaguePassDesc: 'NBA 공식 스트리밍 구독',
    chESPNPlus: 'ESPN+',
    chESPNPlusDesc: 'ESPN 스트리밍 구독',
    chEurosport: 'Eurosport',
    chEurosportDesc: '유럽 스포츠 스트리밍',
    chMLBtv: 'MLB.tv',
    chMLBtvDesc: 'MLB 공식 스트리밍 구독',
    chNFLGamePass: 'NFL Game Pass',
    chNFLGamePassDesc: 'NFL 공식 스트리밍 구독',
    chNHLtv: 'NHL.tv',
    chNHLtvDesc: 'NHL 공식 스트리밍 구독',
    chYoutubeSports: 'YouTube Sports',
    chYoutubeSportsDesc: 'YouTube Sports 채널',
    chDAZN: 'DAZN',
    chDAZNDesc: '글로벌 스포츠 스트리밍 플랫폼',
    disclaimer: '⚠️ 면책 조항: 모든 분석 데이터는 시장 배당률을 기반으로 하며 참고용이며 금융 조언이 아닙니다.',
    disclaimer2: '경기 결과는 많은 요인의 영향을 받습니다. 과거 데이터가 미래 성과를 보장하지 않습니다.',
    heatUnit: '경기',
    // Legal pages
    privacyTitle: '개인정보 보호정책',
    privacyP1: '최종 업데이트: 2026년 6월 3일',
    privacyH1: '데이터 수집',
    privacyP2: 'SportPredict는 다음 데이터만 수집합니다: 언어 기본 설정(브라우저에 로컬 저장), API 캐시 데이터(배당률 정보, 5분 후 만료). 개인 식별 정보는 수집하지 않습니다.',
    privacyH2: '쿠키 사용',
    privacyP3: '본 웹사이트는 localStorage를 사용하여 언어 기본 설정과 쿠키 동의 상태를 저장합니다. Google AdSense를 통해 쿠키를 사용하여 맞춤형 광고를 표시할 수 있습니다. 브라우저 설정에서 쿠키를 관리할 수 있습니다.',
    privacyH3: '제3자 서비스',
    privacyP4: 'The Odds API를 사용하여 스포츠 배당률 데이터를 얻으며, Google AdSense를 사용하여 광고를 표시할 수 있습니다. 이러한 서비스에는 각각의 개인정보 보호정책이 있습니다.',
    privacyH4: 'GDPR 권리',
    privacyP5: 'GDPR에 따라 개인 데이터에 액세스, 수정, 삭제할 권리가 있습니다. 권리를 행사하려면 아래 연락처로 문의하세요.',
    privacyH5: '연락처',
    aboutTitle: 'SportPredict 소개',
    aboutP1: 'SportPredict는 전 세계 스포츠 팬을 위해 시장 데이터 기반의 경기 통계 및 확률 분석을 제공하는 전문 스포츠 데이터 분석 플랫폼입니다.',
    aboutP2: '우리의 사명은 투명한 데이터 시각화를 통해 스포츠 이벤트의 시장 확률과 통계 트렌드를 이해하도록 돕는 것입니다. 모든 분석은 공개 시장 데이터를 기반으로 수학적 모델을 사용하여 계산됩니다.',
    aboutP3: '⚠️ 중요: SportPredict는 어떤 형태의 도박도 제공하지 않고, 수수료를 부과하지 않으며, 도박을 장려하거나 촉진하지 않습니다. 본 사이트의 모든 콘텐츠는 정보 참고 및 학술 연구 목적입니다.',
    termsTitle: '이용약관',
    termsP1: '본 웹사이트를 사용함으로써 다음 약관에 동의하는 것으로 간주됩니다:',
    termsP2: '1. 본 사이트에서 제공하는 모든 데이터와 분석은 참고용이며 베팅 조언을 구성하지 않습니다.',
    termsP3: '2. 사용자는 데이터의 정확성과 적용성을 독립적으로 판단하고 사용 위험을 부담해야 합니다.',
    termsP4: '3. 본 사이트의 콘텐츠는 지적재산권으로 보호되며 허가 없이 복사하거나 재배포할 수 없습니다.',
    termsP5: '4. 본 사이트는 데이터의 실시간성과 정확성을 보장하지 않으며 시장 데이터에 지연이 있을 수 있습니다.',
    cookieText: '본 웹사이트는 쿠키를 사용하여 경험을 향상시키고 Google AdSense를 통해 광고를 표시할 수 있습니다. 계속 사용하면',
    cookieLink: '개인정보 보호정책',
    cookieAccept: '수락',
    footerDisclaimer: '⚠️ SportPredict는 스포츠 데이터 분석 플랫폼으로 도박 서비스를 제공하지 않고 수수료도 부과하지 않습니다. 모든 데이터는 분석 참고용입니다.',
    footerAbout: '회사 소개',
    footerPrivacy: '개인정보 보호정책',
    footerTerms: '이용약관',
    footerContact: '문의하기',
    allEventsGuide: '사이드바에서 리그를 클릭하여 데이터를 로드하세요. 배당률은 5분간 캐시됩니다.',
    clickToLoadOdds: '위의 리그명을 클릭하여 배당률 데이터를 로드하세요',
    apiQuotaExceeded: 'API 할당량을 초과했습니다. 다음 달 재설정을 기다려주세요.',
    apiQuotaHint: '무료 플랜: 월 500회 요청',
    heroTitle: '🏆 SportPredict',
    heroSubtitle: '글로벌 스포츠 배당률 데이터 분석 플랫폼',
    heroTag1: '📊 실시간 배당률',
    heroTag2: '🎯 시장 확률',
    heroTag3: '🔮 차이 분석',
    heroBtnAnalyze: '📊 분석 시작',
    heroBtnFavorites: '⭐ 즐겨찾기',
  },"""

ru_block = """  ru: {
    sidebarLogo: 'Спортивный Анализ',
    sidebarFooter: 'Данные для справки · Не финансовый совет',
    tabMatches: 'Матчи',
    tabCombos: 'Аналитические данные',
    tabDashboard: 'Панель',
    pageTitle: '{emoji} Анализ {sport}',
    homeTeam: 'Хозяева',
    awayTeam: 'Гости',
    draw: 'Ничья',
    confidence: 'Согласованность данных',
    noMatches: 'Нет данных {sport}',
    all: 'Все',
    combo2: '{sport} Двойной комбо',
    combo3: '{sport} Тройной комбо',
    combo2Label: 'Двойной',
    combo3Label: 'Тройной',
    crossCombo: '🌍 Кросс-спортивные инсайты',
    crossCombo3: 'Кросс тройной',
    comboWinRate: 'Общий рейтинг',
    lowRisk: 'Низкий риск',
    mediumRisk: 'Средний риск',
    highRisk: 'Высокий риск',
    dashHitRate: '📊 Распределение подразумеваемой вероятности',
    dashHot: '🔥 Популярные матчи',
    dashArb: '🌟 Возможности расхождения коэффициентов',
    dashArbNone: 'Нет возможностей расхождения',
    dashArbDesc: 'Степень расхождения',
    watchLive: '📺 Смотреть',
    modalTitle: '📺 Официальные каналы трансляций',
    modalDisclaimer: '⚖️ Смотрите через официальные каналы',
    vs: 'vs',
    refreshOdds: 'Обновить коэффициенты',
    loading: 'Загрузка...',
    loadError: 'Ошибка загрузки',
    retry: 'Повторить',
    noData: 'Нет данных',
    oddsCompare: 'Сравнение коэффициентов',
    showOdds: 'Показать коэффициенты',
    hideOdds: 'Скрыть коэффициенты',
    impliedProb: 'Подразумеваемая вероятн.',
    arbOpportunity: 'Расхождение коэффициентов',
    arbProfit: 'Степень расхождения',
    apiRemaining: 'API осталось',
    bookmaker: 'Букмекер',
    bestOdds: 'Лучшие коэффициенты',
    sportSoccer: 'Футбол',
    sportBasketball: 'Баскетбол',
    sportBaseball: 'Бейсбол',
    sportIceHockey: 'Хоккей на льду',
    sportTennis: 'Теннис',
    sportAmericanFootball: 'Американский футбол',
    sportBoxing: 'Бокс',
    sportMma: 'MMA',
    sportCricket: 'Крикет',
    sportRugby: 'Регби',
    sportEsports: 'Киберспорт',
    sportAussieRules: 'Австралийский футбол',
    sportGolf: 'Гольф',
    sportDarts: 'Дартс',
    sportCycling: 'Велоспорт',
    sportSnooker: 'Снукер',
    sportVolleyball: 'Волейбол',
    sportHandball: 'Гандбол',
    sportFutsal: 'Мини-футбол',
    sportTableTennis: 'Настольный теннис',
    sportBadminton: 'Бадминтон',
    chFIFA: 'FIFA+',
    chFIFADesc: 'Официальная стриминговая платформа FIFA',
    chLeagueOfficial: 'Официальная трансляция лиги',
    chLeagueOfficialDesc: 'Официальные цифровые платформы трансляций',
    chNBALeaguePass: 'NBA League Pass',
    chNBALeaguePassDesc: 'Официальная стриминговая подписка NBA',
    chESPNPlus: 'ESPN+',
    chESPNPlusDesc: 'Стриминговая подписка ESPN',
    chEurosport: 'Eurosport',
    chEurosportDesc: 'Европейская спортивная трансляция',
    chMLBtv: 'MLB.tv',
    chMLBtvDesc: 'Официальная стриминговая подписка MLB',
    chNFLGamePass: 'NFL Game Pass',
    chNFLGamePassDesc: 'Официальная стриминговая подписка NFL',
    chNHLtv: 'NHL.tv',
    chNHLtvDesc: 'Официальная стриминговая подписка NHL',
    chYoutubeSports: 'YouTube Sports',
    chYoutubeSportsDesc: 'Канал YouTube Sports',
    chDAZN: 'DAZN',
    chDAZNDesc: 'Глобальная спортивная стриминговая платформа',
    disclaimer: '⚠️ Отказ от ответственности: Все аналитические данные основаны на рыночных коэффициентах, только для справки, не являются финансовым советом.',
    disclaimer2: 'На результаты матчей влияют многие факторы. Прошлые данные не гарантируют будущих результатов.',
    heatUnit: 'матчей',
    // Legal pages
    privacyTitle: 'Политика конфиденциальности',
    privacyP1: 'Последнее обновление: 3 июня 2026 г.',
    privacyH1: 'Сбор данных',
    privacyP2: 'SportPredict собирает только следующие данные: языковые настройки (хранятся локально в браузере), кэшированные данные API (информация о коэффициентах, истекает через 5 минут). Мы не собираем личную идентификационную информацию.',
    privacyH2: 'Использование файлов cookie',
    privacyP3: 'Этот сайт использует localStorage для хранения языковых настроек и статуса согласия на использование файлов cookie. Мы можем использовать файлы cookie через Google AdSense для показа персонализированной рекламы. Вы можете управлять файлами cookie через настройки браузера.',
    privacyH3: 'Сторонние сервисы',
    privacyP4: 'Мы используем The Odds API для получения данных о спортивных коэффициентах и можем использовать Google AdSense для показа рекламы. У этих сервисов есть собственные политики конфиденциальности.',
    privacyH4: 'Права по GDPR',
    privacyP5: 'Согласно GDPR, вы имеете право на доступ, исправление и удаление ваших персональных данных. Для осуществления прав свяжитесь с нами.',
    privacyH5: 'Контакты',
    aboutTitle: 'О SportPredict',
    aboutP1: 'SportPredict — профессиональная платформа анализа спортивных данных, предоставляющая статистику событий и анализ вероятностей на основе рыночных данных для спортивных болельщиков по всему миру.',
    aboutP2: 'Наша миссия — помочь пользователям понять рыночные вероятности и статистические тенденции в спортивных событиях через прозрачную визуализацию данных. Все анализы основаны на общедоступных рыночных данных, рассчитанных с использованием математических моделей.',
    aboutP3: '⚠️ Важно: SportPredict не предоставляет букмекерские услуги, не взимает плату и не поощряет и не продвигает любые формы азартных игр. Всё содержимое сайта предназначено только для информационных целей и академических исследований.',
    termsTitle: 'Условия использования',
    termsP1: 'Используя этот сайт, вы соглашаетесь со следующими условиями:',
    termsP2: '1. Все данные и аналитика на этом сайте предоставляются только для справки и не являются советом по ставкам.',
    termsP3: '2. Пользователи должны самостоятельно оценивать точность и применимость данных и нести риск использования.',
    termsP4: '3. Содержание этого сайта защищено правами интеллектуальной собственности и не может быть скопировано или распространено без разрешения.',
    termsP5: '4. Этот сайт не гарантирует оперативность и точность данных, рыночные данные могут быть задержаны.',
    cookieText: 'Этот веб-сайт использует файлы cookie для улучшения вашего опыта и может отображать рекламу через Google AdSense. Продолжая использовать этот сайт, вы соглашаетесь с нашей',
    cookieLink: 'Политикой конфиденциальности',
    cookieAccept: 'Принять',
    footerDisclaimer: '⚠️ SportPredict — платформа анализа спортивных данных, не предоставляющая букмекерские услуги и не взимающая плату. Все данные предназначены только для аналитических целей.',
    footerAbout: 'О нас',
    footerPrivacy: 'Политика конфиденциальности',
    footerTerms: 'Условия использования',
    footerContact: 'Связаться с нами',
    allEventsGuide: 'Нажмите на лигу в боковой панели для загрузки данных. Коэффициенты кэшируются на 5 минут.',
    clickToLoadOdds: 'Нажмите на лигу выше для загрузки данных о коэффициентах',
    apiQuotaExceeded: 'Квота API превышена. Пожалуйста, дождитесь сброса в следующем месяце.',
    apiQuotaHint: 'Бесплатный тариф: 500 запросов в месяц',
    heroTitle: '🏆 SportPredict',
    heroSubtitle: 'Глобальная платформа анализа данных спортивных коэффициентов',
    heroTag1: '📊 Коэффициенты в реальном времени',
    heroTag2: '🎯 Рыночная вероятность',
    heroTag3: '🔮 Анализ расхождений',
    heroBtnAnalyze: '📊 Начать анализ',
    heroBtnFavorites: '⭐ Избранное',
  },"""

fr_block = """  fr: {
    sidebarLogo: 'Analyse Sportive',
    sidebarFooter: 'Données à titre indicatif · Pas un conseil financier',
    tabMatches: 'Matchs',
    tabCombos: 'Perspectives',
    tabDashboard: 'Tableau de Bord',
    pageTitle: '{emoji} Analyse {sport}',
    homeTeam: 'Domicile',
    awayTeam: 'Extérieur',
    draw: 'Nul',
    confidence: 'Cohérence des données',
    noMatches: 'Aucune donnée {sport}',
    all: 'Tous',
    combo2: '{sport} Combo Double',
    combo3: '{sport} Combo Triple',
    combo2Label: 'Double',
    combo3Label: 'Triple',
    crossCombo: '🌍 Perspectives Multi-Sports',
    crossCombo3: 'Multi-Sports Triple',
    comboWinRate: 'Taux Combiné',
    lowRisk: 'Risque Faible',
    mediumRisk: 'Risque Moyen',
    highRisk: 'Risque Élevé',
    dashHitRate: '📊 Distribution des Probabilités Implicites',
    dashHot: '🔥 Matchs Tendance',
    dashArb: '🌟 Opportunités d\\'Écart de Cotes',
    dashArbNone: 'Aucune opportunité d\\'écart',
    dashArbDesc: 'Taux d\\'écart',
    watchLive: '📺 Regarder en Direct',
    modalTitle: '📺 Chaînes Officielles en Direct',
    modalDisclaimer: '⚖️ Veuillez regarder via des chaînes officielles',
    vs: 'vs',
    refreshOdds: 'Actualiser les Cotes',
    loading: 'Chargement...',
    loadError: 'Erreur de chargement',
    retry: 'Réessayer',
    noData: 'Aucune donnée',
    oddsCompare: 'Comparaison des Cotes',
    showOdds: 'Voir les Cotes',
    hideOdds: 'Masquer les Cotes',
    impliedProb: 'Prob. Implicite',
    arbOpportunity: 'Écart de cotes',
    arbProfit: 'Taux d\\'écart',
    apiRemaining: 'API Restant',
    bookmaker: 'Bookmaker',
    bestOdds: 'Meilleures Cotes',
    sportSoccer: 'Football',
    sportBasketball: 'Basketball',
    sportBaseball: 'Baseball',
    sportIceHockey: 'Hockey sur Glace',
    sportTennis: 'Tennis',
    sportAmericanFootball: 'Football Américain',
    sportBoxing: 'Boxe',
    sportMma: 'MMA',
    sportCricket: 'Cricket',
    sportRugby: 'Rugby',
    sportEsports: 'Esports',
    sportAussieRules: 'Football Australien',
    sportGolf: 'Golf',
    sportDarts: 'Fléchettes',
    sportCycling: 'Cyclisme',
    sportSnooker: 'Snooker',
    sportVolleyball: 'Volleyball',
    sportHandball: 'Handball',
    sportFutsal: 'Futsal',
    sportTableTennis: 'Tennis de Table',
    sportBadminton: 'Badminton',
    chFIFA: 'FIFA+',
    chFIFADesc: 'Plateforme de streaming officielle de la FIFA',
    chLeagueOfficial: 'Diffusion Officielle de Ligue',
    chLeagueOfficialDesc: 'Plateformes de diffusion numérique officielles',
    chNBALeaguePass: 'NBA League Pass',
    chNBALeaguePassDesc: 'Abonnement streaming officiel NBA',
    chESPNPlus: 'ESPN+',
    chESPNPlusDesc: 'Abonnement streaming ESPN',
    chEurosport: 'Eurosport',
    chEurosportDesc: 'Streaming sportif européen',
    chMLBtv: 'MLB.tv',
    chMLBtvDesc: 'Abonnement streaming officiel MLB',
    chNFLGamePass: 'NFL Game Pass',
    chNFLGamePassDesc: 'Abonnement streaming officiel NFL',
    chNHLtv: 'NHL.tv',
    chNHLtvDesc: 'Abonnement streaming officiel NHL',
    chYoutubeSports: 'YouTube Sports',
    chYoutubeSportsDesc: 'Chaîne YouTube Sports',
    chDAZN: 'DAZN',
    chDAZNDesc: 'Plateforme de streaming sportif mondiale',
    disclaimer: '⚠️ Avertissement : Toutes les données d\\'analyse sont basées sur les cotes du marché, à titre indicatif uniquement, et ne constituent pas un conseil financier.',
    disclaimer2: 'Les résultats des matchs sont influencés par de nombreux facteurs. Les données passées ne garantissent pas les performances futures.',
    heatUnit: 'matchs',
    // Legal pages
    privacyTitle: 'Politique de Confidentialité',
    privacyP1: 'Dernière mise à jour : 3 juin 2026',
    privacyH1: 'Collecte de Données',
    privacyP2: 'SportPredict collecte uniquement les données suivantes : préférences linguistiques (stockées localement dans votre navigateur), données de cache API (informations sur les cotes, expirent après 5 minutes). Nous ne collectons pas d\\'informations d\\'identification personnelle.',
    privacyH2: 'Utilisation des Cookies',
    privacyP3: 'Ce site utilise localStorage pour stocker les préférences linguistiques et le statut de consentement aux cookies. Nous pouvons utiliser des cookies via Google AdSense pour afficher des publicités personnalisées. Vous pouvez gérer les cookies via les paramètres de votre navigateur.',
    privacyH3: 'Services Tiers',
    privacyP4: 'Nous utilisons The Odds API pour obtenir les données de cotes sportives, et pouvons utiliser Google AdSense pour afficher des publicités. Ces services ont leurs propres politiques de confidentialité.',
    privacyH4: 'Droits RGPD',
    privacyP5: 'En vertu du RGPD, vous avez le droit d\\'accéder, de corriger et de supprimer vos données personnelles. Pour exercer vos droits, veuillez nous contacter.',
    privacyH5: 'Contact',
    aboutTitle: 'À Propos de SportPredict',
    aboutP1: 'SportPredict est une plateforme professionnelle d\\'analyse de données sportives dédiée à fournir des statistiques d\\'événements et une analyse des probabilités basées sur les données de marché pour les amateurs de sport du monde entier.',
    aboutP2: 'Notre mission est d\\'aider les utilisateurs à comprendre les probabilités de marché et les tendances statistiques dans les événements sportifs grâce à une visualisation transparente des données. Toutes les analyses sont basées sur des données de marché publiques, calculées à l\\'aide de modèles mathématiques.',
    aboutP3: '⚠️ Important : SportPredict ne fournit aucun service de paris ni ne facture de frais, et n\\'encourage ni ne promeut aucune forme de jeu. Tout le contenu de ce site est à titre de référence informative et de recherche académique uniquement.',
    termsTitle: "Conditions d'Utilisation",
    termsP1: 'En utilisant ce site, vous acceptez les conditions suivantes :',
    termsP2: '1. Toutes les données et analyses fournies sur ce site sont à titre indicatif uniquement et ne constituent pas un conseil de paris.',
    termsP3: '2. Les utilisateurs doivent juger indépendamment de l\\'exactitude et de l\\'applicabilité des données et assumer le risque d\\'utilisation.',
    termsP4: '3. Le contenu de ce site est protégé par les droits de propriété intellectuelle et ne peut être copié ou redistribué sans autorisation.',
    termsP5: '4. Ce site ne garantit pas la nature en temps réel et l\\'exactitude des données, et les données de marché peuvent être retardées.',
    cookieText: 'Ce site web utilise des cookies pour améliorer votre expérience et peut afficher des publicités via Google AdSense. En continuant à utiliser ce site, vous acceptez notre',
    cookieLink: 'Politique de Confidentialité',
    cookieAccept: 'Accepter',
    footerDisclaimer: '⚠️ SportPredict est une plateforme d\\'analyse de données sportives qui ne fournit aucun service de paris ni ne facture de frais. Toutes les données sont à titre d\\'analyse indicative uniquement.',
    footerAbout: 'À Propos',
    footerPrivacy: 'Politique de Confidentialité',
    footerTerms: "Conditions d'Utilisation",
    footerContact: 'Contactez-nous',
    allEventsGuide: 'Cliquez sur une ligue dans la barre latérale pour charger les données. Les cotes sont mises en cache pendant 5 minutes.',
    clickToLoadOdds: 'Cliquez sur la ligue ci-dessus pour charger les données de cotes',
    apiQuotaExceeded: 'Quota API dépassé. Veuillez attendre la réinitialisation du mois prochain.',
    apiQuotaHint: 'Formule gratuite : 500 requêtes par mois',
    heroTitle: '🏆 SportPredict',
    heroSubtitle: "Plateforme mondiale d'analyse des cotes sportives",
    heroTag1: '📊 Cotes en direct',
    heroTag2: '🎯 Probabilité du marché',
    heroTag3: '🔮 Analyse des écarts',
    heroBtnAnalyze: "📊 Commencer l'analyse",
    heroBtnFavorites: '⭐ Favoris',
  },"""

de_block = """  de: {
    sidebarLogo: 'Sportanalyse',
    sidebarFooter: 'Daten nur als Referenz · Keine Finanzberatung',
    tabMatches: 'Spiele',
    tabCombos: 'Daten-Einblicke',
    tabDashboard: 'Dashboard',
    pageTitle: '{emoji} {sport} Analyse',
    homeTeam: 'Heim',
    awayTeam: 'Auswärts',
    draw: 'Unentschieden',
    confidence: 'Datenkonsistenz',
    noMatches: 'Keine {sport}-Daten',
    all: 'Alle',
    combo2: '{sport} Doppel-Kombo',
    combo3: '{sport} Dreier-Kombo',
    combo2Label: 'Doppel',
    combo3Label: 'Dreier',
    crossCombo: '🌍 Sportübergreifende Einblicke',
    crossCombo3: 'Sportübergreifend Dreier',
    comboWinRate: 'Kombinierte Gewinnquote',
    lowRisk: 'Niedriges Risiko',
    mediumRisk: 'Mittleres Risiko',
    highRisk: 'Hohes Risiko',
    dashHitRate: '📊 Implizite Wahrscheinlichkeitsverteilung',
    dashHot: '🔥 Trendspiele',
    dashArb: '🌟 Quotendifferenzen',
    dashArbNone: 'Keine Quotendifferenzen',
    dashArbDesc: 'Differenzrate',
    watchLive: '📺 Live ansehen',
    modalTitle: '📺 Offizielle Live-Kanäle',
    modalDisclaimer: '⚖️ Bitte über offizielle Kanäle schauen',
    vs: 'vs',
    refreshOdds: 'Quoten aktualisieren',
    loading: 'Laden...',
    loadError: 'Laden fehlgeschlagen',
    retry: 'Erneut versuchen',
    noData: 'Keine Daten',
    oddsCompare: 'Quotenvergleich',
    showOdds: 'Quoten anzeigen',
    hideOdds: 'Quoten ausblenden',
    impliedProb: 'Impl. Wahrscheinlichkeit',
    arbOpportunity: 'Quotendifferenz',
    arbProfit: 'Differenzrate',
    apiRemaining: 'API verbleibend',
    bookmaker: 'Buchmacher',
    bestOdds: 'Beste Quoten',
    sportSoccer: 'Fußball',
    sportBasketball: 'Basketball',
    sportBaseball: 'Baseball',
    sportIceHockey: 'Eishockey',
    sportTennis: 'Tennis',
    sportAmericanFootball: 'American Football',
    sportBoxing: 'Boxen',
    sportMma: 'MMA',
    sportCricket: 'Cricket',
    sportRugby: 'Rugby',
    sportEsports: 'Esports',
    sportAussieRules: 'Aussie Rules',
    sportGolf: 'Golf',
    sportDarts: 'Darts',
    sportCycling: 'Radsport',
    sportSnooker: 'Snooker',
    sportVolleyball: 'Volleyball',
    sportHandball: 'Handball',
    sportFutsal: 'Futsal',
    sportTableTennis: 'Tischtennis',
    sportBadminton: 'Badminton',
    chFIFA: 'FIFA+',
    chFIFADesc: 'Offizielle FIFA-Streaming-Plattform',
    chLeagueOfficial: 'Offizielle Liga-Übertragung',
    chLeagueOfficialDesc: 'Offizielle digitale Übertragungsplattformen',
    chNBALeaguePass: 'NBA League Pass',
    chNBALeaguePassDesc: 'Offizielles NBA-Streaming-Abo',
    chESPNPlus: 'ESPN+',
    chESPNPlusDesc: 'ESPN-Streaming-Abo',
    chEurosport: 'Eurosport',
    chEurosportDesc: 'Europäisches Sport-Streaming',
    chMLBtv: 'MLB.tv',
    chMLBtvDesc: 'Offizielles MLB-Streaming-Abo',
    chNFLGamePass: 'NFL Game Pass',
    chNFLGamePassDesc: 'Offizielles NFL-Streaming-Abo',
    chNHLtv: 'NHL.tv',
    chNHLtvDesc: 'Offizielles NHL-Streaming-Abo',
    chYoutubeSports: 'YouTube Sports',
    chYoutubeSportsDesc: 'YouTube Sports-Kanal',
    chDAZN: 'DAZN',
    chDAZNDesc: 'Globale Sport-Streaming-Plattform',
    disclaimer: '⚠️ Haftungsausschluss: Alle Analysedaten basieren auf Marktquoten, nur als Referenz, keine Finanzberatung.',
    disclaimer2: 'Spielergebnisse werden von vielen Faktoren beeinflusst. Vergangene Daten garantieren keine zukünftige Leistung.',
    heatUnit: 'Spiele',
    // Legal pages
    privacyTitle: 'Datenschutzerklärung',
    privacyP1: 'Letzte Aktualisierung: 3. Juni 2026',
    privacyH1: 'Datenerhebung',
    privacyP2: 'SportPredict erhebt nur folgende Daten: Spracheinstellungen (lokal im Browser gespeichert), API-Cache-Daten (Quoteninformationen, verfallen nach 5 Minuten). Wir erheben keine personenbezogenen Identifikationsdaten.',
    privacyH2: 'Cookie-Nutzung',
    privacyP3: 'Diese Website verwendet localStorage zum Speichern von Spracheinstellungen und Cookie-Zustimmungsstatus. Wir können Cookies über Google AdSense verwenden, um personalisierte Werbung anzuzeigen. Sie können Cookies über Ihre Browsereinstellungen verwalten.',
    privacyH3: 'Drittanbieter-Dienste',
    privacyP4: 'Wir verwenden The Odds API, um Sportquotendaten zu erhalten, und können Google AdSense verwenden, um Werbung anzuzeigen. Diese Dienste haben eigene Datenschutzrichtlinien.',
    privacyH4: 'DSGVO-Rechte',
    privacyP5: 'Gemäß DSGVO haben Sie das Recht, Ihre personenbezogenen Daten einzusehen, zu korrigieren und zu löschen. Um Ihre Rechte auszuüben, kontaktieren Sie uns bitte.',
    privacyH5: 'Kontakt',
    aboutTitle: 'Über SportPredict',
    aboutP1: 'SportPredict ist eine professionelle Sportdatenanalyse-Plattform, die Sportbegeisterten weltweit marktdatenbasierte Ereignisstatistiken und Wahrscheinlichkeitsanalysen bietet.',
    aboutP2: 'Unsere Mission ist es, Nutzern durch transparente Datenvisualisierung zu helfen, Markt Wahrscheinlichkeiten und statistische Trends bei Sportereignissen zu verstehen. Alle Analysen basieren auf öffentlichen Marktdaten, die mit mathematischen Modellen berechnet werden.',
    aboutP3: '⚠️ Wichtig: SportPredict bietet keine Wettdienstleistungen an, erhebt keine Gebühren und fördert oder unterstützt keine Form des Glücksspiels. Alle Inhalte auf dieser Website dienen nur der Informationsreferenz und akademischen Forschung.',
    termsTitle: 'Nutzungsbedingungen',
    termsP1: 'Durch die Nutzung dieser Website stimmen Sie den folgenden Bedingungen zu:',
    termsP2: '1. Alle auf dieser Website bereitgestellten Daten und Analysen dienen nur als Referenz und stellen keine Wettberatung dar.',
    termsP3: '2. Nutzer sollten die Genauigkeit und Anwendbarkeit der Daten unabhängig beurteilen und das Nutzungsrisiko tragen.',
    termsP4: '3. Der Inhalt dieser Website ist durch Urheberrechte geschützt und darf ohne Genehmigung nicht kopiert oder weiterverbreitet werden.',
    termsP5: '4. Diese Website garantiert nicht die Echtzeit-Natur und Genauigkeit der Daten, Marktdaten können verzögert sein.',
    cookieText: 'Diese Website verwendet Cookies, um Ihre Erfahrung zu verbessern, und kann Anzeigen über Google AdSense schalten. Durch die weitere Nutzung stimmen Sie unserer',
    cookieLink: 'Datenschutzerklärung',
    cookieAccept: 'Akzeptieren',
    footerDisclaimer: '⚠️ SportPredict ist eine Sportdatenanalyse-Plattform, die keine Wettdienstleistungen anbietet und keine Gebühren erhebt. Alle Daten dienen nur der Analyse.',
    footerAbout: 'Über Uns',
    footerPrivacy: 'Datenschutzerklärung',
    footerTerms: 'Nutzungsbedingungen',
    footerContact: 'Kontakt',
    allEventsGuide: 'Klicken Sie auf eine Liga in der Seitenleiste, um Daten zu laden. Quoten werden 5 Minuten lang zwischengespeichert.',
    clickToLoadOdds: 'Klicken Sie auf die Liga oben, um Quotendaten zu laden',
    apiQuotaExceeded: 'API-Kontingent überschritten. Bitte warten Sie auf die Reset im nächsten Monat.',
    apiQuotaHint: 'Kostenloser Tarif: 500 Anfragen pro Monat',
    heroTitle: '🏆 SportPredict',
    heroSubtitle: 'Globale Sportquoten-Datenanalyse-Plattform',
    heroTag1: '📊 Live-Quoten',
    heroTag2: '🎯 Marktwahrscheinlichkeit',
    heroTag3: '🔮 Abweichungsanalyse',
    heroBtnAnalyze: '📊 Analyse starten',
    heroBtnFavorites: '⭐ Favoriten',
  },"""

# Insert the missing blocks after the ar block
# Find the position right after "  }," of ar block, before "};"
insert_content = '\n' + ja_block + '\n' + ko_block + '\n' + ru_block + '\n' + fr_block + '\n' + de_block + '\n'

content = content[:insert_pos] + insert_content + content[insert_pos:]
print("Step 2 done: Inserted ja, ko, ru, fr, de blocks in I18N\n")

# ============================================================
# STEP 3: Fix garbled characters in NEW_I18N blocks
# ============================================================

# Strategy: For each language in NEW_I18N, find the block and replace
# specific garbled key lines with correct values

new_i18n_start = content.find('const NEW_I18N = {')
new_i18n_end = content.find('};', new_i18n_start) + 2

new_i18n_fixes = {
    'zh': {
        'searchPlaceholder': "'搜索比赛、队伍...'",
        'noFavorites': "'暂无收藏'",
        'favAdded': "'已收藏'",
        'favRemoved': "'已取消收藏'",
        'filterHot': "'🔥 热门'",
        'filterUpcoming': "'⏱ 即将开始'",
        'filterLive': "'🟢 进行中'",
        'filterArb': "'🌟 差异分析'",
        'filterHighAttention': "'👀 高关注度'",
        'timeJustNow': "'刚刚'",
        'timeMinutesLater': "'{n}分钟后'",
        'timeHoursLater': "'{n}小时后'",
        'timeTomorrow': "'明天'",
        'timeDaysLater': "'{n}天后'",
        'timeStarted': "'已开始'",
    },
    'en': {
        'searchPlaceholder': "'Search matches, teams...'",
        'noFavorites': "'No favorites yet'",
        'favAdded': "'Added to favorites'",
        'favRemoved': "'Removed from favorites'",
        'filterHot': "'🔥 Hot'",
        'filterUpcoming': "'⏱ Starting Soon'",
        'filterLive': "'🟢 Live'",
        'filterArb': "'🌟 Discrepancy'",
        'filterHighAttention': "'👀 High Attention'",
        'timeJustNow': "'Just now'",
        'timeMinutesLater': "'{n} min'",
        'timeHoursLater': "'{n}h'",
        'timeTomorrow': "'Tomorrow'",
        'timeDaysLater': "'{n} days'",
        'timeStarted': "'Started'",
    },
    'es': {
        'searchPlaceholder': "'Buscar partidos, equipos...'",
        'noFavorites': "'Sin favoritos'",
        'favAdded': "'Añadido a favoritos'",
        'favRemoved': "'Eliminado de favoritos'",
        'filterHot': "'🔥 Popular'",
        'filterUpcoming': "'⏱ Próximo'",
        'filterLive': "'🟢 En vivo'",
        'filterArb': "'🌟 Discrepancia'",
        'filterHighAttention': "'👀 Alta atención'",
        'timeJustNow': "'Ahora'",
        'timeMinutesLater': "'{n} min'",
        'timeHoursLater': "'{n}h'",
        'timeTomorrow': "'Mañana'",
        'timeDaysLater': "'{n} días'",
        'timeStarted': "'Comenzado'",
    },
    'pt': {
        'searchPlaceholder': "'Buscar jogos, times...'",
        'noFavorites': "'Sem favoritos'",
        'favAdded': "'Adicionado aos favoritos'",
        'favRemoved': "'Removido dos favoritos'",
        'filterHot': "'🔥 Popular'",
        'filterUpcoming': "'⏱ Em breve'",
        'filterLive': "'🟢 Ao vivo'",
        'filterArb': "'🌟 Discrepância'",
        'filterHighAttention': "'👀 Alta atenção'",
        'timeJustNow': "'Agora'",
        'timeMinutesLater': "'{n} min'",
        'timeHoursLater': "'{n}h'",
        'timeTomorrow': "'Amanhã'",
        'timeDaysLater': "'{n} dias'",
        'timeStarted': "'Iniciado'",
    },
    'ar': {
        'searchPlaceholder': "'بحث عن مباريات، فرق...'",
        'noFavorites': "'لا مفضلات'",
        'favAdded': "'أضيف إلى المفضلة'",
        'favRemoved': "'أزيل من المفضلة'",
        'filterHot': "'🔥 رائج'",
        'filterUpcoming': "'⏱ قريباً'",
        'filterLive': "'🟢 مباشر'",
        'filterArb': "'🌟 تباين'",
        'filterHighAttention': "'👀 اهتمام عالي'",
        'timeJustNow': "'الآن'",
        'timeMinutesLater': "'{n} د'",
        'timeHoursLater': "'{n} س'",
        'timeTomorrow': "'غداً'",
        'timeDaysLater': "'{n} أيام'",
        'timeStarted': "'بدأ'",
    },
    'ja': {
        'searchPlaceholder': "'試合、チームを検索...'",
        'noFavorites': "'お気に入りなし'",
        'favAdded': "'お気に入りに追加'",
        'favRemoved': "'お気に入りから削除'",
        'filterHot': "'🔥 人気'",
        'filterUpcoming': "'⏱ 開始間近'",
        'filterLive': "'🟢 試合中'",
        'filterArb': "'🌟 差異分析'",
        'filterHighAttention': "'👀 高注目'",
        'timeJustNow': "'たった今'",
        'timeMinutesLater': "'{n}分後'",
        'timeHoursLater': "'{n}時間後'",
        'timeTomorrow': "'明日'",
        'timeDaysLater': "'{n}日後'",
        'timeStarted': "'開始済'",
    },
    'ko': {
        'searchPlaceholder': "'경기, 팀 검색...'",
        'noFavorites': "'즐겨찾기 없음'",
        'favAdded': "'즐겨찾기 추가'",
        'favRemoved': "'즐겨찾기 제거'",
        'filterHot': "'🔥 인기'",
        'filterUpcoming': "'⏱ 곧 시작'",
        'filterLive': "'🟢 진행 중'",
        'filterArb': "'🌟 차이 분석'",
        'filterHighAttention': "'👀 높은 관심'",
        'timeJustNow': "'방금'",
        'timeMinutesLater': "'{n}분 후'",
        'timeHoursLater': "'{n}시간 후'",
        'timeTomorrow': "'내일'",
        'timeDaysLater': "'{n}일 후'",
        'timeStarted': "'시작됨'",
    },
    'ru': {
        'searchPlaceholder': "'Поиск матчей, команд...'",
        'noFavorites': "'Нет избранных'",
        'favAdded': "'Добавлено в избранное'",
        'favRemoved': "'Удалено из избранного'",
        'filterHot': "'🔥 Популярные'",
        'filterUpcoming': "'⏱ Скоро'",
        'filterLive': "'🟢 В эфире'",
        'filterArb': "'🌟 Расхождение'",
        'filterHighAttention': "'👀 Высокий интерес'",
        'timeJustNow': "'Сейчас'",
        'timeMinutesLater': "'{n} мин'",
        'timeHoursLater': "'{n} ч'",
        'timeTomorrow': "'Завтра'",
        'timeDaysLater': "'{n} дн.'",
        'timeStarted': "'Началось'",
    },
    'fr': {
        'searchPlaceholder': "'Rechercher matchs, équipes...'",
        'noFavorites': "'Aucun favori'",
        'favAdded': "'Ajouté aux favoris'",
        'favRemoved': "'Retiré des favoris'",
        'filterHot': "'🔥 Tendance'",
        'filterUpcoming': "'⏱ Bientôt'",
        'filterLive': "'🟢 En direct'",
        'filterArb': "'🌟 Écart'",
        'filterHighAttention': "'👀 Forte attention'",
        'timeJustNow': "'À l\\'instant'",
        'timeMinutesLater': "'{n} min'",
        'timeHoursLater': "'{n}h'",
        'timeTomorrow': "'Demain'",
        'timeDaysLater': "'{n} jours'",
        'timeStarted': "'Commencé'",
    },
    'de': {
        'searchPlaceholder': "'Spiele, Teams suchen...'",
        'noFavorites': "'Keine Favoriten'",
        'favAdded': "'Zu Favoriten hinzugefügt'",
        'favRemoved': "'Aus Favoriten entfernt'",
        'filterHot': "'🔥 Beliebt'",
        'filterUpcoming': "'⏱ Bald'",
        'filterLive': "'🟢 Live'",
        'filterArb': "'🌟 Differenz'",
        'filterHighAttention': "'👀 Hohe Aufmerksamkeit'",
        'timeJustNow': "'Gerade eben'",
        'timeMinutesLater': "'{n} Min.'",
        'timeHoursLater': "'{n} Std.'",
        'timeTomorrow': "'Morgen'",
        'timeDaysLater': "'{n} Tage'",
        'timeStarted': "'Gestartet'",
    },
}

# For NEW_I18N, use a line-by-line replacement approach
# This avoids the issues with regex on garbled text
lines = content.split('\n')
new_i18n_line_start = content[:new_i18n_start].count('\n') + 1
new_i18n_line_end = content[:new_i18n_end].count('\n') + 1

# Determine which language block each line belongs to
current_lang = None
fixes_applied = 0

for i in range(new_i18n_line_start, min(new_i18n_line_end, len(lines))):
    line = lines[i]
    
    # Check if this line starts a new language block
    for lang in new_i18n_fixes.keys():
        if re.match(r'\s+' + lang + r':\s*\{', line):
            current_lang = lang
            break
    
    if current_lang is None:
        continue
    
    # Check if this line ends the language block
    if line.strip() == '},':
        current_lang = None
        continue
    
    # Try to fix this line if it contains a key from the fixes
    if current_lang in new_i18n_fixes:
        for key, correct_value in new_i18n_fixes[current_lang].items():
            # Match pattern like "    key: '...'  ," or "    key: '...',"
            # The key might be followed by garbled text
            key_match = re.match(r'(\s+' + re.escape(key) + r':\s*)', line)
            if key_match:
                prefix = key_match.group(1)
                # Replace the value part
                # Find the value - everything after the key pattern until the comma at end of line
                # Handle both single and double quoted values
                rest = line[key_match.end():]
                
                # Match '...', or "...", at the end (possibly with trailing whitespace)
                value_match = re.match(r"('.*?'|\".*?\"),?\s*$", rest)
                if value_match:
                    old_value = value_match.group(1)
                    expected_value = correct_value
                    if old_value != expected_value:
                        new_line = prefix + expected_value + ','
                        lines[i] = new_line
                        fixes_applied += 1
                        break
                else:
                    # Value might be garbled beyond recognition
                    # Just replace the whole line
                    new_line = prefix + correct_value + ','
                    lines[i] = new_line
                    fixes_applied += 1
                    break

content = '\n'.join(lines)
print(f"Step 3 done: Applied {fixes_applied} fixes in NEW_I18N blocks\n")

# ============================================================
# STEP 4: Write back as UTF-8
# ============================================================

with open(filepath, 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)

print(f"File saved! Total chars: {len(content)}")
